name: eznerf
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - opencv
  - tqdm
  - jinja2
  - natsort
  - pytorch-cuda # remove this if you don't have a GPU