name: eznerf
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pytorch
  - torchvision
  - opencv
  - tqdm
  - jinja2
  - configargparse
  - pytorch-cuda # remove this if you don't have an NVIDIA GPU